apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    environment: production
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: production
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/trouw-192109/github-mathi123-trouw-frontend:b26a839e2962118e53ae202d4887152c299b2e23
        ports:
        - containerPort: 80