kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    environment: production
    tier: frontend
  ports:
  - protocol: TCP
    port: 443
    name: https
  - protocol: TCP
    port: 80
    name: http
  type: LoadBalancer