apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    name: rest-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rest-api
    spec:
      containers:
      - name: rest-api-container
        image: gcr.io/trouw-192109/github-mathi123-trouw-backend:1e4f74d26e7473cfa9e6846c36c250d4d4247b86
        ports:
        - containerPort: 3000